### PR TITLE
DB version check moved to Java layer

### PR DESCRIPTION
**Pull request by zheins**

### CODE REVIEW

**Comment by n1zea144** [comment]
Whats the change to core/pom.xml - is that to get the db version into GlobalProperties at compile time?  If so, do you need an update to GlobalProperties in this request?

**Comment by zheins** [comment]
GlobalProperties already has the code to get dbversion from portal.properties. However, when I added it, I didn't take into account running the core jar from the command line. The changes to core/pom.xml allow the ${db.version} field in the portal.properties file to be properly filtered at compile time.

**Comment by zheins** [comment]
Do not merge this yet. Going to make a change to the pom filtering.

**Comment by pieterlukasse** [comment]
@zheins, @n1zea144 : I think this PR is OK, except for the pom.xml changes. Could you undo that? Then I'll go ahead and merge this.

**Comment by zheins** [comment]
I'll undo it, but the pom changes are necessary for ${db.version} to be filtered in portal.properties and available in the core jar. I'm making some other changes in a different PR that will fix this though.

**Comment by fedde-s** [comment]
Merged without the last commit in c9a7587c44f3571d887660ed88480724c61e090b.

**Pull request closed without merging**
